name: Daily Scraper

on:
  schedule:
    - cron: "0 3 * * *"  # اجرا هر روز ساعت ۳ صبح UTC
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install beautifulsoup4 requests

    - name: Run script
      run: python main.py

    - name: Commit and push
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add public/sub.txt
        git commit -m "Update subscriptions [auto]" || echo "No changes to commit"
        git push
